# Generated by Django 4.2.5 on 2023-10-01 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Providers',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('cname', models.CharField(max_length=50, verbose_name='Name')),
                ('ceoname', models.CharField(max_length=50, verbose_name='CEO Name')),
                ('caddress', models.CharField(max_length=150, verbose_name='Company Address')),
                ('ctype', models.CharField(max_length=25, verbose_name='Company Type')),
                ('otherctype', models.CharField(max_length=25, verbose_name='Company Type')),
                ('cdescription', models.CharField(max_length=500, verbose_name='Company Description')),
                ('cphone', models.CharField(max_length=20, verbose_name='Company Phone Number')),
                ('website', models.CharField(max_length=100, verbose_name='Company Website')),
                ('empno', models.IntegerField(verbose_name='No Of Employees')),
                ('fyear', models.IntegerField(verbose_name='Founded Year')),
                ('logo', models.ImageField(upload_to='company/', verbose_name='Company Logo in jpg/png Format')),
                ('clicense', models.CharField(max_length=100, verbose_name='License number')),
                ('licensefile', models.FileField(upload_to='license/', verbose_name='Company Licence in pdf Format')),
                ('status', models.CharField(default='Not Verified', max_length=20, verbose_name='Current Status')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verification Status')),
                ('role', models.CharField(default='provider', max_length=100)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Seekers',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('dob', models.DateField(default=datetime.date.today, verbose_name='Date of Birth')),
                ('loc', models.CharField(max_length=50, verbose_name='Location')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone No')),
                ('qual', models.CharField(max_length=25, verbose_name='Qualification')),
                ('oqual', models.CharField(max_length=25, verbose_name='Other Qualification')),
                ('exp', models.CharField(max_length=25, verbose_name='Work Experience')),
                ('skills', models.CharField(max_length=150, verbose_name='Skills')),
                ('resume', models.FileField(default=0, max_length=254, upload_to='candidate/resume/', verbose_name='Upload Resume')),
                ('aadhaar', models.CharField(max_length=25, verbose_name='Aadhaar No')),
                ('pro_pic', models.FileField(default=0, max_length=254, upload_to='candidate/images/', verbose_name='Upload Photos')),
                ('role', models.CharField(default='candidate', max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
