# Generated by Django 4.2.5 on 2023-10-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_providers',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='job_seekers',
            name='sid',
        ),
        migrations.AddField(
            model_name='job_providers',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_seekers',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
