# Generated by Django 4.2.5 on 2023-10-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_remove_job_providers_pid_remove_job_seekers_sid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seekers',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_seekers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
